"""add outputgoogle

Revision ID: 25d66537f126
Revises: 6ebcec5aebdf
Create Date: 2017-05-23 00:46:36.221508+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d66537f126'
down_revision = '6ebcec5aebdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bounding_boxes', sa.Column('output_google', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bounding_boxes', 'output_google')
    # ### end Alembic commands ###
