"""add coordinates column to bounding boxes

Revision ID: 3fe092e14408
Revises: b205d57487ee
Create Date: 2017-05-22 13:55:22.213709+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fe092e14408'
down_revision = 'b205d57487ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bounding_boxes', sa.Column('coordinates', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bounding_boxes', 'coordinates')
    # ### end Alembic commands ###
