"""add timestamps

Revision ID: 6ebcec5aebdf
Revises: 3fe092e14408
Create Date: 2017-05-22 14:15:13.663275+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebcec5aebdf'
down_revision = '3fe092e14408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bounding_boxes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(current_timestamp at time zone 'UTC')"), nullable=False))
    op.add_column('bounding_boxes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(current_timestamp at time zone 'UTC')"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bounding_boxes', 'updated_at')
    op.drop_column('bounding_boxes', 'created_at')
    # ### end Alembic commands ###
